Add Dockerfile and initial params
ipab-rad/ros2_ouster_drivers pull request #1
Opened 2024-03-01 17:06 UTC by GreatAlexander

2024-04-15 17:22 UTC, hect95 requested changes

2024-04-15 17:22 UTC, hect95 commented on av_ouster_launch/launch/av_ouster.launch.xml
> +    <arg name="params_file" value="$(find-pkg-share av_ouster_launch)/params/av_ouster_config.yaml"/>
@GreatAlexander  I think this version does not run the nodes inside a container. Is up to us if we want to leave it like that for now. Anyways, we have some fmw updates to the ouster and other ROS2 repo testing

2024-04-15 17:22 UTC, hect95 commented on av_ouster_launch/package.xml
> +  <maintainer email="alex.bordallo@ed.ac.uk">Alejandro Bordallo</maintainer>
Taking into account about the reviewer and author roles in the reviews, should I add myself as a maintainer or will you do it? :)

2024-04-25 15:46 UTC, hect95 requested changes
More changes :)

2024-04-25 15:46 UTC, hect95 commented on runtime.sh
> +    av_ouster_launch_humble $CMD
As discussed docker image name should be: `av_ouster:latest`

2024-04-25 15:46 UTC, hect95 commented on dev.sh
> +    av_ouster_launch_humble
As discussed docker image name should be: `av_ouster:latest`

2024-04-25 19:19 UTC, GreatAlexander commented on dev.sh
> +    av_ouster_launch_humble
Done

2024-04-25 19:19 UTC, GreatAlexander commented on runtime.sh
> +    av_ouster_launch_humble $CMD
Done

2024-04-25 19:23 UTC, GreatAlexander commented on av_ouster_launch/launch/av_ouster.launch.xml
> +    <arg name="params_file" value="$(find-pkg-share av_ouster_launch)/params/av_ouster_config.yaml"/>
Indeed... Given it's 1 node to run as composable, it doesn't sound like it's worth the effort to rework the original driver to make it one.
Also this launch depends on a Python launchfile :vomiting_face: which also flags lots of issues with flake8 ros from pre-commit. Given the Python launchfile is imported from the driver repo, tempted to leave it as is and ignore in pre-commit, unless a brave soul wants to have a go at fixing it :sweat_smile:

2024-04-25 19:28 UTC, hect95 commented on av_ouster_launch/launch/av_ouster.launch.xml
> +    <arg name="params_file" value="$(find-pkg-share av_ouster_launch)/params/av_ouster_config.yaml"/>
Happy to leave it like that. I think the launch file  from the Ouster oficial repo is a bit cleaner. Anyway we will archive this repo soon anyways

2024-04-26 14:52 UTC, hect95 approved these changes
Good to go!

2024-04-29 14:07 UTC, GreatAlexander commented
I'll merge this PR in the repo in case we need it, but we may well remove this fork in future.

2024-04-29 14:07 UTC, merged